### ISSUE TITLE
Debug name for entities

### ISSUE THREAD

**Issue by rogetsss** [outerminds/Entia#15]
I'm debugging quite a lot theses days, and one thing that I find difficult is never knowing what the entity I'm looking at is when stepping into the code. Would it be possible that each entity has a debug name, or something to easy identify it, even if it's not in the release version.

Thanks

**Comment by Magicolo** [comment]
You can always add a component with debug information associated with your Entity when creating it. If you're using Entia.Unity, an _Entia.Components.Debug_ component is already automatically added for you (in DEBUG) when creating an Entity from an EntityReference.

While I understand this may not be the most convenient way to debug entities since it requires to get the debug component, it can work as a current solution. As for a more integrated solution, I will look at what can be achieved without compromising performance or extensibility.

**Comment by rogetsss** [comment]
A debug component is not really a solution for the the friction I experience, more specifically when I'm steping into a piece of code and I need to know which entity is what. I don't want to have to add some additionnal code to find a debug component everywhere I want to identify an entity. Also, adding a component on each entity is cumbersome to begin with. But it would be awesome if you could investigate!

**Comment by Magicolo** [comment]
I've got a few ideas in mind to facilitate debugging of entities in a debugger. I will try them out in a week or two.

**Comment by Magicolo** [comment]
Implemented a solution that will display components of the 'Entity' when inspecting it with a debugger. It will be available in the next release.
