### ISSUE TITLE
Why everything is a struct ?

### ISSUE THREAD

**Issue by ryuukk** [outerminds/Entia#8]
Hi

I wonder why everything is a struct, i understand you want cache locality, but with C# it's impossible to achieve without bloated the code with ref everywhere, and some code might still have to use reference types ex: libraries, assets, poco etc

I am forced to use struct for component and system ? can i still use class ? if i do, will i get performance penalty because of choice to focus on structs for Entia internals ?

Thanks!

**Comment by Magicolo** [comment]
Hi,

As you mentioned, the main reason for using structs for Entia's components/resources/messages is for cache locality and for preventing from generating garbage. Therefore you will not be able to use class components/resources/messages with the framework. This doesn't mean that you cannot use classes within a component/resource/message since otherwise the framework would be extremely restrictive (arrays, dictionaries, etc. would not be allowed). So if you need to use a class from a library or from any source, you can absolutely put it inside a struct component/resource/message. It is true though that Entia code will have to make extensive use of the 'ref' keyword.

For other concepts such as systems the choice to make them structs is more of a design decision. The whole idea behind an ECS framework is to promote composition and classes may tempt OOP impulses to make base classes and inherit from them. Flattened program structures are easier to change and are usually easier to understand.
